dist: xenial
language: python
python:
  - '3.6'
  - '3.7'
  - '3.8'
install:
  - pip install -r requirements-local.txt
  - pip install coverage django_coverage_plugin
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - coverage run ./manage.py test
after_script:
  - coverage xml
  - if [[ "$TRAVIS_PULL_REQUEST" == "false" ]]; then ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT; fi
env:
  global:
    - PYTHONPATH=.
    - DJANGO_SETTINGS_MODULE=testsettings
    - CC_TEST_REPORTER_ID=9ccca9dd50c20259c5a6c9bdcadf336de75e0469093d1724d04bcd499bc7eb3a